networks:
  pac-network:
    driver: bridge
services:
  pac-authentication:
    build:
      context: "./src/authentication"
    container_name: "pac-authentication"
    ports:
      - "8001:8001"
    env_file:
      - ./envs/.env
    command: ["fastapi", "run", "./app/Authentication.py", "--port", "8001"]
    networks:
      - pac-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 2s
      retries: 5
  pac-challenges:
    build:
      context: "./src/challenges"
    container_name: "pac-challenges"
    ports:
      - "8002:8002"
    env_file:
      - ./envs/.env
    command: ["fastapi", "run", "./app/Challenges.py", "--port", "8002"]
    networks:
      - pac-network
    depends_on:
      - pac-authentication
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 2s
      retries: 5
  pac-monitoring:
    build:
      context: "./src/monitoring"
    container_name: "pac-monitoring"
    ports:
      - "8003:8003"
    env_file:
      - ./envs/.env
    command: ["fastapi", "run", "./app/Monitoring.py", "--port", "8003"]
    networks:
      - pac-network
    depends_on:
      - pac-authentication
      - pac-challenges
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 2s
      retries: 5
  pac-agentic:
    build:
      context: "./src/agentic"
    container_name: "pac-agentic"
    ports:
      - "8004:8004"
    env_file:
      - ./envs/.env
    command: ["fastapi", "run", "./app/Agentic.py", "--port", "8004"]
    networks:
      - pac-network
    depends_on:
      - pac-authentication
      - pac-challenges
      - pac-monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 10s
      timeout: 2s
      retries: 5
